require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/**/*'
   - 'vendor/bundle/**/*'
   - 'spec/spec_helper.rb'
   - 'spec/rails_helper.rb'
   - 'spec/support/**/*'
   - 'config/**/*'
   - '**/Rakefile'
   - '**/Gemfile'

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/ClosingParenthesisIndentation:
  Enabled: false

Metrics/LineLength:
  Max: 100
  AllowURI: true

Layout/FirstParameterIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Style/SignalException:
  EnforcedStyle: semantic

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

Style/AndOr:
  EnforcedStyle: conditionals

Style/MultilineBlockChain:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: False

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - '*.gemspec'
