inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/BlockLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
